production:
 create_from_remote: no
 use.user.selected.activities: yes

development:
 application_diagnosis_concept: QECH Emergency Diagnosis List
 application_generic_medication: Diabetes Medication
 filing.number.limit: 300
 create_from_remote: no
 use.user.selected.activities: false
 advanced.prescription.interface: true

test: &TEST
 create_from_remote: no
 use.user.selected.activities: yes

cucumber:
  <<: *TEST
