production:
 create_from_remote: no
 use.user.selected.activities: yes

development:
 filing.number.limit: 300
 create_from_remote: no
 use.user.selected.activities: yes

test: &TEST
 create_from_remote: no
 use.user.selected.activities: yes

cucumber:
  <<: *TEST
